### ISSUE TITLE
Calls Clientside AgriCraft Functions on Server

### ISSUE THREAD

**Issue by nephatrine** [NicJames2378/IEClocheCompat#5]
Crash when tried to use on dedicated server. Getting a NoSuchMethod for one of the agricraft api methods. Using AgriCraft-2.12.0-1.12.0-a6 and ieclochecompat-2.1.7-dev.330.

```
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from IE Cloche Compat (ieclochecompat)
Caused by: java.lang.NoSuchMethodError: com.infinityraider.agricraft.api.v1.plant.IAgriPlant.getPrimaryPlantTexture(I)Lnet/minecraft/util/ResourceLocation;
	at com.nicjames2378.IEClocheCompat.CRUD.compats.AgriCraft.AgriClocheCompat$AgricraftCropHandler.register(AgriClocheCompat.java:259)
	at com.nicjames2378.IEClocheCompat.CRUD.compats.AgriCraft.AgriClocheCompat.initialize(AgriClocheCompat.java:318)
	at com.nicjames2378.IEClocheCompat.recipes.Recipes.initialize(Recipes.java:22)
	at com.nicjames2378.IEClocheCompat.proxy.CommonProxy.PostInit(CommonProxy.java:26)
	at com.nicjames2378.IEClocheCompat.Main.PostInit(Main.java:34)
```

**Comment by NicJames2378** [comment]
Oops! Left in some debug code I meant to remove. I'll get you a (should be) fixed version compiled very soon. Sorry!

**Comment by NicJames2378** [comment]
A fix has been uploaded to CurseForge ([ieclochecompat-2.1.7-dev.335.jar](https://minecraft.curseforge.com/projects/ie-cloche-compat/files/2657465)). Apologies for the delay. Please let me know if the issue has been rectified for you.

**Comment by nephatrine** [comment]
Wow, that was super quick. Unfortunately this version isn't working in singleplayer anymore and still won't load on dedicated server. Error (from both SSP and SMP) is regarding a different method now With the previous version it did work in SSP so not sure why that would stop working.

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from IE Cloche Compat (ieclochecompat)
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.getTagCompound()Lnet/minecraft/nbt/NBTTagCompound;
	at com.nicjames2378.IEClocheCompat.CRUD.compats.AgriCraft.AgriClocheCompat.canRegister(AgriClocheCompat.java:381)
	at com.nicjames2378.IEClocheCompat.CRUD.compats.AgriCraft.AgriClocheCompat.initialize(AgriClocheCompat.java:317)
	at com.nicjames2378.IEClocheCompat.recipes.Recipes.initialize(Recipes.java:22)
	at com.nicjames2378.IEClocheCompat.proxy.CommonProxy.PostInit(CommonProxy.java:26)
	at com.nicjames2378.IEClocheCompat.Main.PostInit(Main.java:34)
```

**Comment by NicJames2378** [comment]
I have created a Discord Server for my mod(s). Would you mind visiting it for a little while? I Am unable to reproduce the error on my end and would like to see how you are generating it, if you don't mind. https://discord.gg/8mpQQMb

**Comment by NicJames2378** [comment]
Please try with this version and see if your error persists. If it does, contact me through the Discord link above so I may troubleshoot this further.
[IE Cloche Compat 2.1.7-d.350.zip](https://github.com/NicJames2378/IEClocheCompat/files/2734983/IE.Cloche.Compat.2.1.7-d.350.zip)

**Comment by nephatrine** [comment]
Sorry forgot to get back to you. This works great now. ty
